### PR TITLE
Don't redeclare EnumSet as Set

### LINKED ISSUE #179: UseCollectionInterfaces breaks EnumSet iteration
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.7.1

## What is the smallest, simplest way to reproduce the problem?

```java
        EnumSet<?> values = EnumSet.allOf(MyEnum.class);
        for (Enum<?> e : values) {
            // something
        }
```

## What did you expect to see?
no change

## What did you see instead?

```java
        Set<?> values = EnumSet.allOf(MyEnum.class);
        for (Enum<?> e : values) {
            // something
        }
```
That doesn't compile anymore. For other subclasses of Set, using the super class for the declaration doesn't change the template argument. For EnumSet it does, because EnumSet is defined with a template argument `Enum<E>` extending `Set<E>`. Therefore anx code needing then Enum typing will not compile anymore.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

If some maintainer agrees, I would try to exclude EnumSet from the applicable types in this recipe.

### PR DESCRIPTION
**Pull request by Bananeweizen**
That changes the type of the generic, potentially breaking iterators.

Fixes #179

## What's changed?
Exclude EnumSet from the recipe.

## Anything in particular you'd like reviewers to focus on?
I've not commented in the recipe but rather created a unit test to verify that EnumSet doesn't get back into the recipe on accident.

### Checklist
- [X] I've added unit tests to cover both positive and negative cases

### CODE REVIEW

File: src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java [hunk 1]
```diff
@@ -663,47 +664,51 @@ class Test {
...
           )
         );
     }
 
+    @Test
+    @Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/179")
+    void enumSetNotInRecipe() {
+        assertThat(UseCollectionInterfaces.rspecRulesReplaceTypeMap).doesNotContainKey("java.util.EnumSet");
+    }
+
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java:695]: Not sure we'd need this with the above test adapted already, right? Saves us from tying too strongly to implementation details (and having to maintain that) if we remove this one.
```suggestion
```

**Review by timtebeek — APPROVED** [review]

**Comment by timtebeek** [comment]
Thanks again! Really helpful all these fixes left and right.
